import { createHmac, timingSafeEqual } from 'node:crypto';

/**
 * The Trugi NIP settlement rail.
 *
 * A Nigerian merchant funds their vault by bank transfer, not by holding a token. The rail that
 * makes that possible is a dedicated virtual account: the merchant is issued a NUBAN of their own,
 * money sent to it is credited to them specifically, and the provider posts a signed notification
 * the moment it lands.
 *
 * ── What is real here, and what is not ────────────────────────────────────────────────────
 *
 * The provisioning is real: an account number is derived for each merchant, structurally valid
 * under the CBN NUBAN standard including its check digit, and stable — the same merchant always
 * gets the same account, which is what makes a dedicated account *dedicated*. The notification
 * path is real: credits arrive as signed webhooks, the signature is verified before anything
 * moves, and a reference that has already settled is rejected rather than paid twice.
 *
 * The counterparty is not real. No licensed provider is behind this, no naira moves, and the
 * credit notification is generated by us rather than by a bank. That requires a payment licence
 * and a signed partner agreement, neither of which is a thing code can produce. Every surface
 * that shows an account says `sandbox` for that reason.
 *
 * Swapping in a live provider — Paystack, Monnify, Flutterwave, or Trugi proper — means replacing
 * `provisionAccount` with their create-virtual-account call and pointing their webhook at the
 * route that already exists. The settlement half downstream does not change.
 */

/** Providus Bank's CBN institution code. The partner this rail is designed against. */
const BANK_CODE = '101';
const BANK_NAME = 'Providus Bank';

export type RailMode = 'sandbox' | 'live';

export interface VirtualAccount {
  bank: string;
  bankCode: string;
  accountNumber: string;
  accountName: string;
  /** The merchant this account settles to. */
  beneficiary: string;
  mode: RailMode;
}

/**
 * The CBN NUBAN check digit.
 *
 * Every Nigerian account number carries one, computed over the bank code and the nine-digit
 * serial with the weight pattern 3-7-3 repeating. Generating numbers without it would produce
 * strings that look like accounts and fail validation in any system that checks — including the
 * one that would eventually replace this.
 */
function nubanCheckDigit(bankCode: string, serial: string): string {
  const digits = `${bankCode}${serial}`;
  const weights = [3, 7, 3, 3, 7, 3, 3, 7, 3, 3, 7, 3];
  const sum = digits
    .split('')
    .reduce((total, digit, i) => total + Number(digit) * weights[i], 0);
  const check = (10 - (sum % 10)) % 10;
  return String(check);
}

/**
 * Derive a merchant's dedicated account.
 *
 * Deterministic in the merchant's address, so it survives a reload, a new device, and a
 * redeployment — a dedicated account that changed between visits would not be dedicated, and
 * money sent to yesterday's number would have nowhere to land.
 */
export function provisionAccount(
  beneficiary: string,
  businessName: string,
  mode: RailMode = 'sandbox',
): VirtualAccount {
  const seed = createHmac('sha256', 'temi:trugi:nuban').update(beneficiary.toLowerCase()).digest();
  // Nine digits from the digest, first digit forced non-zero so the NUBAN reads as a real one.
  let serial = '';
  for (let i = 0; i < 9; i++) serial += String(seed[i] % 10);
  serial = (Number(serial[0]) === 0 ? '1' : serial[0]) + serial.slice(1);

  return {
    bank: BANK_NAME,
    bankCode: BANK_CODE,
    accountNumber: serial + nubanCheckDigit(BANK_CODE, serial),
    accountName: `Tèmi / ${businessName || 'Merchant'}`,
    beneficiary,
    mode,
  };
}

/** A credit notification, in the shape a NIP provider posts when money lands. */
export interface CreditNotification {
  /** The provider's own id for this credit. Settling twice against it is refused. */
  reference: string;
  accountNumber: string;
  /** Kobo, because that is how naira is quoted on the wire. */
  amountKobo: number;
  currency: 'NGN';
  beneficiary: string;
  sessionId: string;
  paidAt: string;
}

const SIGNING_KEY = process.env.TRUGI_WEBHOOK_SECRET ?? 'temi-trugi-sandbox-signing-key';

/** The signature a provider sends alongside the body, over the raw bytes. */
export function signNotification(rawBody: string): string {
  return createHmac('sha512', SIGNING_KEY).update(rawBody).digest('hex');
}

/**
 * Verify a notification before acting on it.
 *
 * An endpoint that moves money on an unauthenticated POST is an endpoint anyone can drain. The
 * comparison is constant-time so a signature cannot be discovered a byte at a time.
 */
export function verifyNotification(rawBody: string, signature: string | null): boolean {
  if (!signature) return false;
  const expected = signNotification(rawBody);
  const a = Buffer.from(expected);
  const b = Buffer.from(signature);
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

export const koboToNaira = (kobo: number): number => kobo / 100;
export const nairaToKobo = (naira: number): number => Math.round(naira * 100);
